### ISSUE TITLE
Converting from dataless to StationXML shifts epoch times to local from UTC

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/stationxml-seed-converter#10]
Converting the attached dataless SEED volume:
[ARCES_DATALESS.SEED.gz](https://github.com/iris-edu/stationxml-seed-converter/files/2426793/ARCES_DATALESS.SEED.gz)

results in a shift of epoch times from UTC to local time zone.

First channel epoch time from `rdseed -s -f ARCES_DATALESS.SEED`
```
...
B052F22     Start date:                            1987,242
B052F23     End date:                              1999,256,23:59
...
```

Convert to StationXML using:
`$ java -jar stationxml-converter-1.0.10.jar --xml ARCES_DATALESS.SEED -so 'source' -o out.xml`

Same channel epoch time is:
```XML
<Channel locationCode="00" code="SHZ" startDate="1987-08-30T07:00:00.000"
                endDate="1999-09-14T06:59:00.000">
```

My computers local time zone is UTC-7, and both times have been shifted by 7 hours.

**Comment by timronan** [comment]
Refer to the convert's new Github page [seed-xml-converter](https://github.com/iris-edu/seed-xml-converter). The new converter does not do this.
