### ISSUE TITLE
Station Names in Dataless are right justified instead of left

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-seed-converter#15]
Blockette 50 Field 3 (And other fixed length ASCII fields) are right justified, but the seed standard requires left justification.

I would open this issue on java-4-seed (or fix), but I am not finding that repository on github.

**Comment by yazan-iris** [comment]
The project is here https://github.com/yazan-iris/java-4-seed <https://github.com/yazan-iris/java-4-seed>

I have committed a fix with a version set to SNAPSHOT.  Let me know if you still have access issues.

Yazan

**Comment by timronan** [comment]
Java-4-seed has been fixed to output dataless as left justified. The converter has been updated to include the new java-4-seed jar in commit 1355ca7aa85862f7e4f11cf58cd0ce164b0356f0. The jar is available at the stationxml-seed-converter-2.0.0 release or can be built from source.
