### ISSUE TITLE
Metadata without gain information is defaulting to 0-value sensitivity

### ISSUE THREAD

**Issue by amkearns-usgs** [iris-edu/stationxml-seed-converter#18]
Examples of this show up in metadata such as from VM* stations where the entire response data is a polynomial response of the form 0+(1E-1)x. With no sensitivity information the converter defaults to specifying a sensitivity (gain stage 0) where the sensitivity is specified as 0.

We believe it would be more appropriate to default to 1.0 in these cases based on how gain is defined (gain of 0 would imply an empty signal).

**Comment by yazan-iris** [comment]
can you please be more specific in your example, I need access to the original file.  When I read your description, I understand a channel with polynomial response without stage 0.  The converter then insert stage 0 of type 58, is this what you are saying?

**Comment by amkearns-usgs** [comment]
I believe we understand each other, yes. A channel has, according to rdseed, a blockette 52 and 62 in dataless input and that is all its data for a given epoch. We run it through the converter to XML and back to dataless and find that there is now also a blockette 58 for it, all fields at 0.

Here's example input and output. Again, it's VM* channels where we find this in particular.
[CU-dataless.zip](https://github.com/iris-edu/stationxml-seed-converter/files/2681920/CU-dataless.zip)

**Comment by yazan-iris** [comment]
I agree this is a bug, the solution however is not to provide a stage 0 since it is missing in the original file.

**Comment by amkearns-usgs** [comment]
I think that would be an acceptable solution. I assumed that the converter automatically producing a stage 0 (since as I've been led to understand it's derived from other response stages) would still be desired behavior. Not having a stage 0 in the output shouldn't be any worse for us than not having it in the input.

**Comment by rcasey-iris** [comment]
Seems reasonable, but I think that the source dataless should consider having the lone polynomial going from Volts to COUNTS be a Stage 0 Blockette 62.  The SEED manual summarizes it this way (emphasis mine):

Use this blockette to characterize the response of the entire system or a component (e.g. sensor) of the system. When used in stage 0 the polynomial should describe the conversion from the sample values to Earth units. When used within the response cascade (stages >= 1) the polynomial should represent a single component of the system. A stage 0 polynomial should always be present to facilitate conversion of the data to Earth units when any component of the system is described using a polynomial. As a simplification, a complete response may be specified with only a polynomial specified in stage 0. (See examples below.) When any system is described using a polynomial, a blockette 58 should not be present in stage 0 (sensitivity); unless the polynomial describes a linear transform a total sensitivity scalar cannot be correct. Unlike most other response blockettes that describe a filter representing a component during data acquisition, the polynomial describes a function to be applied to the data. 


	I don't know if your tools have been working fine with a lone Stage 1, but it doesn't fit to what I gather from the documentation.

	-Rob

**Comment by timronan** [comment]
To date, the converter has been designed to convert from stationXML to dataless and visa versa. In its current ideology, the converter is not supposed to do any validation except that the seed schema cannot be  violated when converting from stationXML to dataless seed. This is why @yazan-iris suggest not providing a stage 0 when only a stage 1 is provided in the original document. Even though this output stnXML fails the description outlined by the Seed Manual, that failure should be caught by the [StationXML-Validator](https://github.com/iris-edu/StationXML-Validator) and the converted file can be manually altered by the user. By preventing the converter from making auto corrections and adjustments the information of the original file stays intact and accurate and precise correction can be applied by the user. 

The 2.0.1 release has been updated and a new jar file is attached. Please pull the code/jar and test. We made a test dataless, [CU_VM_.zip](https://github.com/iris-edu/stationxml-seed-converter/files/2692636/CU_VM_.zip), which only contains a few VM channels of interest. If the new jar is satisfactory please close the issue.

**Comment by amkearns-usgs** [comment]
VM channels in question do not have added sensitivity/gain stages when run on the most recent build. Thanks for your cooperation!
