### ISSUE TITLE
Pole-zero response error terms appear to be removed during conversion

### ISSUE THREAD

**Issue by amkearns-usgs** [iris-edu/stationxml-seed-converter#19]
Found an example of this in CU-ANWB ch. BH2 data epoch from 2010-041 to 2018-218, as taken from FDSN. First two poles have real error term 2.191350E-04 and imaginary error term 2.394350E-04. Running a conversion of this to and from dataless seed produces response information where these have been replaced with 0.

**Comment by yazan-iris** [comment]
Fixed

**Comment by amkearns-usgs** [comment]
This issue seems to be persisting from XML conversion into seed. In the attached XML several channels have error terms. Using rdseed with option '-s' on the converted dataless, we get output that matches the input except for the error terms.

This is not an issue going to XML from dataless (in fact this XML is the result of conversion from a dataless file). This appears to be the only remaining discrepancy between input and output.
[CU-missing-error-terms.zip](https://github.com/iris-edu/stationxml-seed-converter/files/2704354/CU-missing-error-terms.zip)
