### ISSUE TITLE
caseOne() test in XmlSeedXmlTest.java is failing

### ISSUE THREAD

**Issue by amkearns-usgs** [iris-edu/stationxml-seed-converter#20]
Build failed as a result of this error. Specific issue is on line 50, response.getStage().size() produces a value of 4 instead of the expected 3. Local copy is currently up to date.

Debugging the response object reveals that stage 0 data is present in the list returned by getStage() but that this object has null fields.

**Comment by timronan** [comment]
Try re-pulling and compiling again. Not all of the code was committed in an earlier commit.
