### ISSUE TITLE
Error terms still being lost in XML->Dataless conversion

### ISSUE THREAD

**Issue by amkearns-usgs** [iris-edu/stationxml-seed-converter#21]
Couldn't re-open the previous ticket about this issue so I've created a new one.

Removal of error terms in pole-zero cases, among others, seems to be persisting from XML conversion into seed. In the attached XML several channels have error terms. Using rdseed with option '-s' on the converted dataless, we get output that matches the input except for the error terms.

This is not an issue going to XML from dataless (in fact this XML is the result of conversion from a dataless file). This appears to be the only remaining discrepancy between input and output.

[CU-missing-error-terms.zip](https://github.com/iris-edu/stationxml-seed-converter/files/2704525/CU-missing-error-terms.zip)

As an example, check ANWB 00.LH1 from 2010 to 2018. The first two poles should have real error of 2.191350E-04 and imaginary error 2.394350E-04

**Comment by timronan** [comment]
The converter has been updated and tested. A release has been added to as stationxml-seed-converter-2.0.1. Please test the code and verify that the patch is adequate.

**Comment by amkearns-usgs** [comment]
Checking this over with the most recent version appears to work. The file under test in the issue ticket now has proper error terms from xml to dataless based on output from rdseed.
