### ISSUE TITLE
Converter crashing on large datasets (full CI stationXML)

### ISSUE THREAD

**Issue by amkearns-usgs** [iris-edu/stationxml-seed-converter#23]
Input is the file produced from the following command:
```sh
curl -L -o CI.xml "https://service.iris.edu/fdsnws/station/1/query?net=CI&level=response&format=xml&includecomments=true&nodata=404"
```
It is a roughly 1.3 GB file, the largest of those for the networks we currently place under analysis.

When we run the converter like so (we've tried with higher than 10g max heap sizes as well):
```sh
java -jar -Xmx10g [converter].jar --input CI.xml --output CI.dataless
```
we get the following error:
```sh
java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at edu.iris.dmc.seed.record.VolumeRecord.getBytes(VolumeRecord.java:54)
	at edu.iris.dmc.seed.io.SeedBufferedOutputStream.write(SeedBufferedOutputStream.java:22)
	at edu.iris.dmc.seed.writer.SeedFileWriter.write(SeedFileWriter.java:42)
	at edu.iris.dmc.seed.writer.SeedFileWriter.write(SeedFileWriter.java:36)
	at edu.iris.dmc.station.converter.XmlToSeedFileConverter.convert(XmlToSeedFileConverter.java:45)
	at edu.iris.dmc.station.converter.XmlToSeedFileConverter.convert(XmlToSeedFileConverter.java:29)
	at edu.iris.dmc.station.converter.XmlToSeedFileConverter.convert(XmlToSeedFileConverter.java:19)
	at edu.iris.dmc.station.Application.convert(Application.java:106)
	at edu.iris.dmc.station.Application.run(Application.java:62)
	at edu.iris.dmc.station.Application.main(Application.java:18)

Error: null
```

We're not sure if the reason for this is that the file is large or if there's another, subtler issue at play that is only obvious because the file size is so large.

**Comment by amkearns-usgs** [comment]
I am examining the source of the java-4-seed library based on the stack trace above (since the IDE is able to access it from the jar file) and I am not sure that the problem here is one caused by the size of the CI dataless file despite it being the largest one we analyze -- I believe that would be returning an OutOfMemoryException if it was simply too large to be held in the array.

As a result we're not really sure what the issue at play could be here, but it's one we're likely unable to examine and fix for ourselves.

**Comment by yazan-iris** [comment]
Let me look into this, will update by tomorrow.

**Comment by amkearns-usgs** [comment]
Is this issue still being worked on? I've seen that there were some recent pushes to the codebase relatively recently but with the ticket open wasn't sure if there was still work/testing to be done on it or not.

**Comment by timronan** [comment]
@amkearns-usgs we are working on this issue and are close to a solution. When testing this patch, we found an inconstancy in a different software stack so are trying to determine if the artifact is occurring in the converter or our other legacy software. If you email me at tronan@iris.washington.edu, I can give a further explanation and can provide a test jar.

**Comment by timronan** [comment]
A new converter version, 2.0.4-SNAPSHOT, has been released. Please find the jar at https://github.com/iris-edu/stationxml-seed-converter/releases. We addressed this issue in commits e0c40235ef4188d14977dc66e98e293d7394c0c4 and e0c40235ef4188d14977dc66e98e293d7394c0c4. Please test this issue using the new jar. 

Usage: When converting a large .xml file use the flag `--large`.

`java -jar PATH/TO/stationxml-seed-converter-2.0.4-SNAPSHOT.jar --input /PATH/TO/StnXML_file.xml --output /PATH/TO/StnXML_file.dataless --large`

**Comment by amkearns-usgs** [comment]
I have been able to convert CI.xml as downloaded above into dataless; checking the file against rdseed appears to produce correct information. However, I am finding that attempting to convert back from the new dataless file to xml produces the following output:
```
May 07, 2019 11:26:45 AM edu.iris.dmc.seed.builder.BlocketteBuilder build010
INFO: Building: 0100040V2.412~~2019,126,21:27:33.0000~~~
May 07, 2019 11:27:26 AM edu.iris.dmc.seed.io.RecordInputStream next
INFO: Expected 8 but read only -1 bytes
```

This is true whether or not I include the `--large` parameter.

**Comment by yazan-iris** [comment]
This indicates the end of file, do you have the xml generated correctly??

**Comment by amkearns-usgs** [comment]
I may have replied slightly prematurely. I am going to do some more work to verify the XML but it appears that the XML was generated properly; I thought at first that an empty file was being generated, but I was trying to load it through terminal in vim and didn't realize that it was about 1.7GB large. I will continue to investigate the outputted file for any oddities.

**Comment by timronan** [comment]
The output messaging that you noted above was removed by commit 54d97abfd5db870c06fe1456161554dbf35410e8 in the java-4-seed program. I will redeploy this java-4-seed to maven and the next converter build will not contain the stdout described above.

**Comment by timronan** [comment]
Has this issue been resolved satisfactorily? I will close this issue in 7 days unless there is an additional bug that needs to be addressed.

**Comment by amkearns-usgs** [comment]
We've not had a chance to look at this satisfactorily but we should be able to check on our own at this point. You should hear back from either James or myself in a day or two running this with CI and probably one other dataset.

**Comment by timronan** [comment]
Thanks for checking in on this issue.
