### ISSUE TITLE
File does not convert - likely a number format issue

### ISSUE THREAD

**Issue by ketchum-usgs** [iris-edu/stationxml-seed-converter#29]
The attached file gives:
acqdb::ketchum:XMLIMPORT>java -jar ~vdl/bin/stationxml-seed-converter-2.0.5-SNAPSHOT.jar --input ~metadata/XMLIMPORT/ROIPH5.xml --output ROIPH5.dataless
May 29, 2019 8:00:57 PM edu.iris.dmc.station.Application exitWithError
SEVERE: 
Error: null

Error: null

An older version (2.0.2) had this detail about this same file:

java.lang.NumberFormatException: Couldn't format number!-0.0   +-0.00000E+00 [12  13 ]
        at edu.iris.dmc.io.SeedStringBuilder.append(SeedStringBuilder.java:263)
        at edu.iris.dmc.seed.control.station.B053.toSeedString(B053.java:83)
        at edu.iris.dmc.seed.AbstractBlockette.getLength(AbstractBlockette.java:74)
        at edu.iris.dmc.seed.Volume.add(Volume.java:166)
        at edu.iris.dmc.station.converter.XmlToSeedDocumentConverter.convert(XmlToSeedDocumentConverter.java:208)
        at edu.iris.dmc.station.converter.XmlToSeedDocumentConverter.convert(XmlToSeedDocumentConverter.java:48)
        at edu.iris.dmc.station.converter.XmlToSeedFileConverter.convert(XmlToSeedFileConverter.java:41)
        at edu.iris.dmc.station.converter.XmlToSeedFileConverter.convert(XmlToSeedFileConverter.java:29)
        at edu.iris.dmc.station.converter.XmlToSeedFileConverter.convert(XmlToSeedFileConverter.java:19)
        at edu.iris.dmc.station.Application.convert(Application.java:106)
        at edu.iris.dmc.station.Application.run(Application.java:62)
        at edu.iris.dmc.station.Application.main(Application.java:18)

Error: Couldn't format number!-0.0   +-0.00000E+00 [12  13 ]

I do not see a number formatted like -0.0 or +0.00 in the file.

[ROIPH5.txt](https://github.com/iris-edu/stationxml-seed-converter/files/3234286/ROIPH5.txt)

**Comment by timronan** [comment]
This issue has been addressed by commit [47252fce6363476f583204302e4f688ba3487ee4](https://github.com/yazan-iris/fdsn-stationxml-model/commit/47252fce6363476f583204302e4f688ba3487ee4) in the [fdsn-stationxml-model](https://github.com/yazan-iris/fdsn-stationxml-model) . The Github releases directory has also been updated. Please get or compile the new jar and rerun the test. 

Also note, the xml file provided seems to have some errors. The  ROIPH5.xml file does not pass a validation test against the FDSN-stationXML .xsd schema because it contains a Stroage format attribute:
`<StorageFormat>Steim2</StorageFormat>`
This attribute is not outlined in the FDSN-stationXML schema. Furthermore, in response stage 1 the `Zero number` index starts at 3 rather than 0. 

```
 <Stage number="1">
            <PolesZeros resourceId="ResponsePAZ#20160218095753.862363.8141" name="IPH5.2013.016.DF">
              <InputUnits>
                <Name>PA</Name>
              </InputUnits>
              <OutputUnits>
                <Name>V</Name>
              </OutputUnits>
              <PzTransferFunctionType>LAPLACE (RADIANS/SECOND)</PzTransferFunctionType>
              <NormalizationFactor>0.940681</NormalizationFactor>
              <NormalizationFrequency>0.3</NormalizationFrequency>
              <Zero number="3">
                <Real minusError="0.00000" plusError="0.00000">-4.4005</Real>
                <Imaginary minusError="0.00000" plusError="0.00000">0</Imaginary>
              </Zero>
              <Zero number="4">
                <Real minusError="0.00000" plusError="0.00000">-0.0026</Real>
                <Imaginary minusError="0.00000" plusError="0.00000">0.0024</Imaginary>
              </Zero>
              <Zero number="5">
                <Real minusError="0.00000" plusError="0.00000">0</Real>
                <Imaginary minusError="0.00000" plusError="0.00000">-0.0024</Imaginary>
              </Zero>
```

**Comment by chad-iris** [comment]
> <StorageFormat>Steim2</StorageFormat>

Note that this element was removed [StationXML 1.1](http://www.fdsn.org/xml/station/) (recently adopted by the FDSN), as it has little to no value in metadata.

**Comment by timronan** [comment]
Has this issue been resolved satisfactorily? I will close this issue in 7 days unless there is an additional bug that needs to be addressed.
