### ISSUE TITLE
release 1.0.10: no main manifest attribute

### ISSUE THREAD

**Issue by petrrr** [iris-edu/stationxml-seed-converter#3]
I have tried to update to version 1.0.10 of the converter, using the released jar file, but I only get error message: `no main manifest attribute, in stationxml-converter-1.0.10.jar`.  
```
petr% java -jar /Users/petr/bin/stationxml-converter-1.0.10.jar --help
no main manifest attribute, in /Users/petr/bin/stationxml-converter-1.0.10.jar
```

Looks like this problem specific to this release jar file, while the former 1.0.9 from SeisCode just works file. I also note that the jar file is significantly smaller, so it is probably reasonable to assume that something is missing from the this file.

```
petr% ls -la stationxml-converter-1.0.*
-rw-r--r--@ 1 petr  staff    110197 22 May 19:09 stationxml-converter-1.0.10.jar
-rw-r--r--@ 1 petr  staff  16068350  1 Feb  2017 stationxml-converter-1.0.9.jar
```

**Comment by yazan-iris** [comment]
Should work now
