### ISSUE TITLE
What license is this software under?

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-seed-converter#31]
I do not see a LICENSE.md or similiar file in the project.

What license is this software being released as?

Thanks

**Comment by rcasey-iris** [comment]
Thanks for bringing this to our attention.  Please review the repo to confirm that this is licensed as GPL v3.  The source code header was added to Application.java in the source stack.

**Comment by jholland-usgs** [comment]
Thanks for clearing it up.
