### ISSUE TITLE
Order of stations in output dataless does not match the order of the entries in Blockette 11, problem for rdseed.

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/stationxml-seed-converter#34]
The converter appears to duplicate a full station entry when converting from StationXML to dataless SEED.

**Comment by chad-iris** [comment]
Full test case is below.

request file:
```
% cat req.txt 
2H      CONZ     --      BHZ 2019-04-07T15:45:08Z 2019-04-07T16:15:08Z
AI      BELA     04      BHZ 2019-04-07T15:45:08Z 2019-04-07T16:15:08Z
AI      BELA     --      BHZ 2019-04-07T15:45:08Z 2019-04-07T16:15:08Z
```

FetchData run:
```
% FetchData -l req.txt -o out.mseed -X sta.xml -sd . -rd .
```

Convert StationXML to dataless using lastest release and latest SNAPSHOT:
```
java -jar stationxml-seed-converter-2.0.2.jar --input sta.xml --output 2.0.2.dataless
java -jar stationxml-seed-converter-2.0.6-SNAPSHOT.jar --input sta.xml --output 2.0.6.dataless
```

Converting these dataless RESP and SAC PZ for comparison:
```
rdseed -f ../2.0.2.dataless -R -p
... <snip,this is same output as for the 2.0.6 SNAPSHOT below>

% rdseed -f ../2.0.6.dataless -R -p
<< IRIS SEED Reader, Release 5.3.1 >>
	p = output poles and zeros
	R = print response data (with addressing for evresp)
	Taking input from ../2.0.6.dataless
Writing RESPONSE file: RESP.AI.BELA..BHZ
Writing RESPONSE file: RESP.AI.BELA.04.BHZ
Writing RESPONSE file: RESP.2H.CONZ..BHZ
Writing RESPONSE file: RESP.AI.BELA..BHZ
Writing RESPONSE file: RESP.AI.BELA.04.BHZ
Writing SAC poles and zeros file:SAC_PZs_AI_BELA_BHZ__2009.016.00.00.00.0000_2599.365.23.59.59.99999
Writing SAC poles and zeros file:SAC_PZs_AI_BELA_BHZ_04_2012.020.13.00.00.0000_2599.365.23.59.59.99999
Writing SAC poles and zeros file:SAC_PZs_2H_CONZ_BHZ__2016.353.00.00.00.0000_2020.366.23.59.59.99999
Writing SAC poles and zeros file:SAC_PZs_AI_BELA_BHZ__2009.016.00.00.00.0000_2599.365.23.59.59.99999
Writing SAC poles and zeros file:SAC_PZs_AI_BELA_BHZ_04_2012.020.13.00.00.0000_2599.365.23.59.59.99999
```

That looks like the BELA channels got written out twice.
Sure enough the RESP file contains them twice.  The SAC PZ file does not, perhaps the file was overwritten instead of appended-to.

Checking the listings of SEED via `rdseed -s` and it does look those stations and channels are duplicated.

So the converter is duplicating the BELA station, but not the CONZ station.

**Comment by rcasey-iris** [comment]
Did some checking with other tools on the converted dataless

1.  seedsniff -- The BELA stations and channels are not duplicated.  Response looks normal.
2.  PDCC 3.8.1 -- The BELA stations and channels are not duplicated.  Response looks normal.
3.  Jrdseed 0.10 -- The BELA stations and channels are not duplicated.  SAC PZ output not duplicated, RESP is fine except very long coefficients broken into two parts by SHAPE.

Suggest we look at this with some tweezers, but the issue might be with rdseed.  Please confirm.

**Comment by rcasey-iris** [comment]
Example:

`rob$ java -jar /Users/rob/bin/JrdseedVer0.10.1.jar
<< Java SEED Reader, Release 0.10.1 237  >>
Input  File (/dev/nrst0) or 'Quit' to Exit: 2.0.6.dataless
Output File (stdout)	:
Volume #  [(1)-N]	:
Options [acCsSpRtde]	: Rp
Station List (ALL)	:
Channel List (ALL)	:
Network List (ALL)	:
Loc Ids (ALL ["--" for spaces])	:
Input  File (/dev/nrst0) or 'Quit' to Exit:`

`rob$ ls
2.0.6.dataless		RESP.2H.CONZ..BHZ	RESP.AI.BELA..BHZ	RESP.AI.BELA.04.BHZ`

**Comment by rcasey-iris** [comment]
Confirmed that rdseed 5.3.1 appends to the RESP file, writing out the BELA station response stack twice.  The SACPZ file seems to get overwritten on the second pass, so no duplicate.

Confirmed the issue happens in v5.2 of rdseed as well.  This behavior has been around for a while.  Not sure if it's due to the extended length FIR filters, or some other factor.

See issue being filed about Blockette 11 stations being listed in reverse index order by the converter.

**Comment by timronan** [comment]
Can you please attach the .xml and dataless file you are inspecting? I want to read the metadata.

**Comment by chad-iris** [comment]
> seedsniff -- The BELA stations and channels are not duplicated. Response looks normal.
> ...

Ah, interesting.  Confirmed.

> See issue being filed about Blockette 11 stations being listed in reverse index order by the converter.

Bingo, excellent find!  Using said tweezers (i.e. vim), I switched the order of the entries in the B11 and rdseed (5.3.1) wrote only single copies out.

To illustrate the order differencing, below is seedsniff output for the 2.0.6.dataless.

```
logrec 1 type 'V '
        type 010 len 0066 : 02.412~~2019,322,21:33:01.0000~IRIC DMC~Converted from XML~
        type 011 len 0032 : 002BELA 000004CONZ 000003
```
...
Note the order of BELA then CONZ.

Later in the dataless, the first station to appear is CONZ:
```
logrec 3 type 'S '

        type 050 len 0125 : CONZ -77.532898+167.082306+3433.00001000Mt Erebus site CONZ~0013210102016,353,00:00:00.0000~2020,366
                          : ,23:59:59.0000~N2H
```

followed by BELA:
```
logrec 4 type 'S '

        type 050 len 0154 : BELA -77.875000-034.626900+0262.00002000BELGRANO II Permanent Argentinean Antarctic Base~00332101020
                          : 09,016,00:00:00.0000~2599,365,23:59:59.0000~NAI
```

Switching the order of the entries in B11, logical record 1, made rdseed do the right thing (not duplicate).

**Comment by chad-iris** [comment]
Closing as a symptom of #36
