### ISSUE TITLE
Converting does nothing and provides no indication of success or error with input as URL

### ISSUE THREAD

**Issue by chad-iris** [iris-edu/stationxml-seed-converter#35]
Trying to convert from an fdsnws-station service call:

```
% java -jar stationxml-seed-converter-2.0.6-SNAPSHOT.jar \
  --input 'http://service.iris.edu/fdsnws/station/1/query?network=AI&station=BELA&location=--&channel=BHZ&level=response' \
  --output AI_BELA.dataless
%
```
Results in nothing, no further output to the console, no output file.

Downloading the XML to a file and running the converter with the file produces a dataless SEED file.

**Comment by timronan** [comment]
The converter does not support downloading and converting files if given a URL as the input argument. The user must provided the program an input file that is stored in the the user's local directory structure. Currently, the documentation is buried but we have previously discussed this issue and decided it is out of the loaders scope to accept input URLs as arguments. 

We could consider providing users with an output message if they provide a nonexistant local file as an input argument.

**Comment by chad-iris** [comment]
This is not about the loader, but the converter.  Not sure what 'documentation is buried' means, but the converter has this help message:
```
...
Usage:
java -jar stationxml-converter.jar [arguments]
	-h, aliases = "--help", usage = "print this message"
	--input, usage = "Input as a file or URL"
	--output, usage = "Output file path and name"
```

So we need to remove the "or URL" part if we're not going to support it. 

> We could consider providing users with an output message if they provide a nonexistant local file as an input argument.

Definitely want to print an error for that.  It's unexpected that the error is not reported.

It would also be handy to change the exit code to 1 or some other non-zero value if the converter exists with an error.

**Comment by timronan** [comment]
We will update the output messages and change the exit code.

**Comment by timronan** [comment]
The output messages and exit codes have been updated: 
```
java -jar ./stationxml-seed-converter-2.0.6-SNAPSHOT-jar-with-dependencies.jar --help
```
returns 
```
Usage:
java -jar stationxml-converter.jar [arguments]
	-h, aliases = "--help", usage = "print this message"
	--input, usage = "Input file path and name"
	--output, usage = "Output file path and name"
```
```
java -jar ./stationxml-seed-converter-2.0.6-SNAPSHOT-jar-with-dependencies.jar --input 'http://service.iris.edu/fdsnws/station/1/query?network=AI&station=BELA&location=--&channel=BHZ&level=response' --output AI_BELA.dataless
```
returns
```
Nov 19, 2019 3:02:41 PM edu.iris.dmc.station.Application exitWithError
SEVERE: 
Error: Couldn't process file http:/service.iris.edu/fdsnws/station/1/query?network=AI&station=BELA&location=--&channel=BHZ&level=response

(base) tronan:target tronan$ echo $?
1
```
Notice the exit code of 1 when requested. 

```
java -jar ./stationxml-seed-converter-2.0.6-SNAPSHOT-jar-with-dependencies.jar --input ./NM_HENM.2019111910.xml --output  ./NM_HENM.2019111910.xml.dataless
```

leads to
```
echo $?
0
```
