### ISSUE TITLE
converter from XML to dataless for two stations yields Blk 11 indices out of order

### ISSUE THREAD

**Issue by rcasey-iris** [iris-edu/stationxml-seed-converter#36]
A recent FetchData request with this pattern:

> 2H      CONZ     --      BHZ 2019-04-07T15:45:08Z 2019-04-07T16:15:08Z
> AI      BELA     04      BHZ 2019-04-07T15:45:08Z 2019-04-07T16:15:08Z
> AI      BELA     --      BHZ 2019-04-07T15:45:08Z 2019-04-07T16:15:08Z

Resulted in a Blockette 11 with two entries, record index 4, followed by record index 3.  The order of these indices should be ascending, not decending.

>         type 011 len 0032 : 002BELA 000004CONZ 000003

**Comment by chad-iris** [comment]
As noted in #34, this causes a problem when the using rdseed with such dataless files.  In this case the BELA station is duplicated on output of rdseed, at least to metadata files (e.g. RESP).

**Comment by timronan** [comment]
Is this documented in the Seed Manual? I don't see a reference to ascending vs descending order in the seed manual under blockette 11:field 5.

**Comment by timronan** [comment]
B11 output from converted example file:

0110032002CONZ 000003BELA                                                                                                                                                                                                            000004
