### ISSUE TITLE
Running without arguments gives unhelpful error messgage

### ISSUE THREAD

**Issue by CTrabant** [iris-edu/stationxml-seed-converter#37]
using version 2.0.7:

```
% java -jar stationxml-seed-converter-2.0.7-SNAPSHOT.jar
Nov 20, 2019 10:33:26 AM edu.iris.dmc.station.Application exitWithError
SEVERE: 
Error: Invalid number of arguments
```

Previous versions, tested with v2.0.6, return the help/usage message.

We should either add something along the lines of "Try -h to see usage" or print the usage message itself as it used to do.

**Comment by timronan** [comment]
This issue is being addressed in branch repackage-seed-stationxml-converter. Upon branch merge we will re-comment on this issue.

**Comment by timronan** [comment]
This issue has been resolved in release [2.1.0-RC-1](https://github.com/iris-edu/stationxml-seed-converter/releases/tag/stationxml-seed-converter-2.1.0-RC-1). Please download the new jar and comment or close the issue if satisfied. Thanks for reporting.

**Comment by chad-iris** [comment]
Cool, now there is a help message, much better.

One note: the message says "StationXml", but the name of the format is "StationXML" (capital XML).

This issue is fixed, so I'll close it, but please fix the help message.

**Comment by timronan** [comment]
Thanks for catching that typo. It's been fixed.
