### ISSUE TITLE
stationxml-seed-converter needs LC_ALL=C

### ISSUE THREAD

**Issue by jmsaurel** [iris-edu/stationxml-seed-converter#38]
Hello,

I just figured out that stationxml-seed-converted needs the environment in which it works to be set-up with English numeric output, ie `LC_ALL=C`.

If this not the case, for example in a French environment, numbers are incorrectly parsed or written and the stationXML to SEED dataless conversion is completely wrong.
All numbers are completely mis-translated (number and exponant).
The resulting response as nothing to do with the original.

This should at least be clearly indicated at the top of the documentation.

In bash, you can overcome this by issuing the following export before using the converter.
`export LC_ALL="C"`

In tcsh or csh, use the following.
`setenv LC_ALL C`

**Comment by timronan** [comment]
Thanks for the comment. The stationxml-seed-convert's documentation has been updated to include your suggestions. The text is below. 

> The stationxml-seed-converted is built in an English language enviroment and assumes users have similar settings. If a user's enviroment is not C locale please instantiate a C locale enviroment using export LC_ALL="C" for bash, or setenv LC_ALL C for tcsh/csh.

Please let us know if this paragraph does not sufficiently solve this issue. Once again, thanks for working with us.
