### ISSUE TITLE
Master branch has quit building

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-seed-converter#39]
The latest build is erroring. I am not able to produce a jar file. This is as of 2019-12-20.

```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   XmlToSeedFileConverterTest.commentConversion » StackOverflow
[ERROR]   XmlToSeedFileConverterTest.t1 » StackOverflow
[ERROR]   XmlToSeedFileConverterTest.t2 » StackOverflow
[ERROR]   XmlToSeedFileConverterTest.t3 » StackOverflow
[ERROR]   XmlToSeedFileConverterTest.t4 » StackOverflow
[INFO] 
[ERROR] Tests run: 24, Failures: 0, Errors: 5, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.310 s
[INFO] Finished at: 2019-12-20T14:55:27-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project stationxml-seed-converter: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jholland/dev/stationxml-seed-converter/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by timronan** [comment]
We are working on it right now. I'll let you know when everything is stable again. You will need to pull java-4-seed as well.

**Comment by jholland-usgs** [comment]
Thanks

**Comment by jholland-usgs** [comment]
Any update on this?  Thanks

**Comment by timronan** [comment]
I just redeployed the last stable instance of java-4-seed and the stationxml-seed-converter to the Maven Snapshot repository. We are still in a development phase of java-4-seed which is likely interrupting your workflow when building the converter. We will let you know as soon as it is ready; it may not be ready until early next week. We have been refactoring.

**Comment by jholland-usgs** [comment]
Thanks for the update.

**Comment by jholland-usgs** [comment]
Any update on this ticket?

**Comment by timronan** [comment]
We reverted both java-4-seed and the stationxml-seed-converter to their last stable commits. We are adopting a better practice branching model for the future of this project. The master branch should be stable and should be able to compile. Please test this and let us know if it does not.

**Comment by jholland-usgs** [comment]
Thank you so much.

It now compiles

The validator is also broken, should I open an issue there?

**Comment by timronan** [comment]
I will fix the validator right now. One second. Thanks for being patient we appreciate it.

**Comment by jholland-usgs** [comment]
Thank you.

**Comment by timronan** [comment]
The stationxml-validator should now be working. We had to rebase the validator to a few merges back, so if you have outstanding validator code to commit you need to stash it before updating the project.
