### ISSUE TITLE
Outpu units in M**3

### ISSUE THREAD

**Issue by Pequegnat** [iris-edu/stationxml-seed-converter#4]
Hi everybody,
stationxml-converter-1.0.10.jar fails to convert dataless presenting :
B052F08     Signal units lookup:     0             M&ast;&ast;3/M&ast;&ast;3 - Volumetric strain 
Those units a legal in SEED (i am not wrong).
Would it be possible to fix it ?
Thanks in advance
[station.CL.MOKI.dataless.gz](https://github.com/iris-edu/stationxml-seed-converter/files/2114425/station.CL.MOKI.dataless.gz)

Best regards
Catherine Péquegnat
RESIf-DC
Grenoble
France

**Comment by chad-iris** [comment]
The m&ast;&ast;3/m&ast;&ast;3 unit is included in the allowed list on the [Unit-name-overview-for-IRIS-StationXML-validator](https://github.com/iris-edu/StationXML-Validator/wiki/Unit-name-overview-for-IRIS-StationXML-validator) page, so it should be allowed by the validator.

Thanks for reporting.

**Comment by Pequegnat** [comment]
Thanks.
Indeed, FROM stationxml (with m**3/m**3) TO dataless SEED it is OK
The problem  is : FROM dataless with  M**3/M**3 to stationxml that we cannot convert

**Comment by yazan-iris** [comment]
Catherine


I am not clear about the file you attached to this email, is it the original seed or the converted one?  Do you start with seed -> xml or xml -> seed?  Please send me all the original files with detailed description.

Thank you

**Comment by Pequegnat** [comment]
Hi Yazan,
the original file is the dataless one.
I want to convert it into stationXML.
I know there is some problems with sensor sensitivity expressed with polynomial forms, but this not what is first in scope. 
The firt problems seed to bee the unit expression M**3/M**3; with cuade the exception in java.

Thanks for your help !
Catherine

**Comment by yazan-iris** [comment]
Hi Catherine

B034 lookup sequence code should start with 1 and not 0 as it is in your case.  You have the following entries for b034:

034   0039  000   M**3/M**3~Volumetric strain ~
034   0027  001   RADIANS~radians ~
034   0066  002   V/M/S~volt per meter per second (analogical seismometer~
034   0025  003   MV~milli-Volt ~
034   0021  004   PA~Pascal ~
034   0020  005   S~second ~
034   0069  006   V/M/S**2~volt per meter per second squared (analogical acc~
034   0025  007   CM~centimeter ~
034   0033  008   COUNTS~digital counts ~
034   0019  009   T~Tesla ~
034   0035  010   COUNTS/V~count per volt ~
034   0035  011   DEGREES~degrees (angle) ~    000003A
034   0035  012   RAD/S~radian per second ~
034   0019  013   G~gramm ~
034   0019  014   M~meter ~
034   0020  015   HZ~Hertz ~
034   0024  016   KG~kilogramm ~
034   0024  017   KM~kilometer ~
034   0058  018   M/S**2~meter per second squared (acceleration) ~
034   0046  019   RAD/S**2~radian per second squared ~
034   0031  020   C~centigrad degrees ~
034   0018  021   V~volt ~
034   0025  022   UV~micro-Volt ~
034   0043  023   M/S~meter per second (velocity) ~
034   0035  024   DEGREES~degrees (angle) ~
034   0029  025   NANO-M~nano-metre ~
034   0020  026   A~Ampere ~
034   0034  027   BIT~binary unity (0/1) ~
034   0061  028   M/S**2~meter per second per second (acceleration) ~
034   0027  029   RADIANS~radians ~
034   0018  030   V~volt ~
034   0040  031   MICRO-M~micro-meter (micron) ~
034   0025  032   MM~millimeter ~


You must start at 001 and re-sequence if you are to use the converter.   This is documented in the SEED manual.  In addition don’t forget to update b062-05 and all referencing blockets, example:

0620129P01000021MB…..

By the way, we have no use for b052-08 when converting; we derive the information from stage 0 input-units (b058-b062).  Also, channels require endtimes.

Let me know if you any further help.


Yazan

**Comment by timronan** [comment]
@yazan-iris correct in his comment above, the dataless is formatted incorrectly. M^3/M^3 can't be converted in this file because the file is incorrectly mapping blockette 34.
