### ISSUE TITLE
Add support for non-IRIS originating organizations and custom Volume Labels

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-seed-converter#40]
This is a feature request.
Currently the converter bakes the below quote in to the dataless volumes.

```
> B010F08     Originating Organization:                                            IRIC DMC
> B010F09     Volume Label:                                              Converted from XML
```
However, dataless we produce is not from the IRIS DMC and we would like to customize the volume label as well.

I propose that two optional parameters be added to the CLI.
```
--origin [custom originating organization]
--label [custom volume label]
```
These would allow overriding of the corresponding fields in the dataless output.
They would be ignored unless converting XML to Dataless.

I am willing to add these if your team is currently busy.

**Comment by timronan** [comment]
We are discussing what to do about this. We will provide more information when we figure out the best way to manage this request.

**Comment by timronan** [comment]
This issue has been resolved in release [2.1.0-RC-1](https://github.com/iris-edu/stationxml-seed-converter/releases/tag/stationxml-seed-converter-2.1.0-RC-1). Please download the new jar and comment or close the issue if satisfied. Thanks for reporting.

**Comment by timronan** [comment]
@jholland-usgs have you had a chance to test this feature? Thanks for looking into it.

**Comment by jholland-usgs** [comment]
No, but I will do so now.

**Comment by timronan** [comment]
Thank you

**Comment by jholland-usgs** [comment]
It works great. I tested going over the SEED lengths and it truncates as expected to match SEED format.

Thanks for including this.
