### ISSUE TITLE
Units converted from dataless are unexpectedly modified

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-seed-converter#42]
Units being converted from Dataless to xml are being changed in unexpected ways.

Reproduction:
All files are attached. [unit_conversion.zip](https://github.com/iris-edu/stationxml-seed-converter/files/4130251/unit_conversion.zip)

1. Convert from Dataless to XML
```java -jar stationxml-seed-converter-2.0.8-SNAPSHOT.jar --input ccm.seed --output ccm2.xml```
2. View the dataless using rdseed
```
B054F05     Response in units lookup:              COUNTS - Digital Counts
B054F06     Response out units lookup:             COUNTS - Digital Counts
```
3. Compare to what was generated in the xml
```
                            <OutputUnits>
<Name>count</Name>
<Description>Digital Counts</Description>
                            </OutputUnits>
```

COUNTS vs count may be synonymous in most circumstances. However, it breaks evaluation in evalresp when we repull our own metadata for verification from IRIS.
```
(mypython) [aringler@igskgacggsaslrs for_alexis]$ evalresp CCM LH2 2019 001 0.02 0.02 1 -f /APPS/metadata/RESPS/RESP.IU.CCM.10.LH2
 EVRESP ERROR (CCM.IU.10.LH2 [File: /APPS/metadata/RESPS/RESP.IU.CCM.10.LH2; Start date: 2018,160,18:00:00.0000; Stage: 2]):
check_units; units found ('COUNT - DIGITAL COUNTS') are not supported,
skipping to next response now
EVRESP FAILED
```

**Comment by timronan** [comment]
The units are converted following this  [unit conversion table](https://github.com/iris-edu/stationxml-seed-converter/wiki/Unit-Convertion). This may be an issue in evalresp that needs to be fixed. This feature could be removed from the converter but had been specifically asked for and is reported as issue #26.

**Comment by rcasey-iris** [comment]
Hi James-

	Are you running evalresp 3.3.3?  The current release (5.0) supports COUNT units.  It's been available since 4.0.x according to the CHANGELOG.

	https://github.com/iris-edu/evalresp <https://github.com/iris-edu/evalresp>

	I'm attempting to validate this on my end.

	-Rob

**Comment by rcasey-iris** [comment]
The test case wasn't clear to me.  I think that what was being evaluated was the XML, so the test line is really:

evalresp CCM LH2 2019 001 0.02 0.02 1 -f ccm2.xml

	Is that correct?  So far, 5.0 seems to work fine.  I get an AMP and a PHASE file without error.

	-Rob

**Comment by jholland-usgs** [comment]
I wasn't actually the one running evalresp. I will ask the originator of this error to comment.

**Comment by aringler-usgs** [comment]
Hello @rcasey-iris 

Thanks for looking into this.  We found this error to be coming from the evalresp in obspy.  I think it is 3.2.3: [https://github.com/obspy/obspy/tree/master/obspy/signal/src/evalresp](url)

I would think this change in conventions is going to break a fair bit of code.  However, I can understand you not wanting to see folks stick with 3.2.3.

**Comment by jholland-usgs** [comment]
Obspy has a ticket open for implementing evalresp 5.0.
https://github.com/obspy/obspy/issues/2379
They were also talking about removing evalresp and rewriting it in python.
https://github.com/obspy/obspy/pull/1718
Neither has moved in about a year.

It appears that this tool simply isn't compatible with obspy in its current state. This should get fixed either here or in obspy. Since the only motivation for COUNTS->count appears to be IRIS tweaking metadata standards, it seems logical that IRIS should resolve this.

@aringler-usgs 
For now we can circumvent this problem on our side. After our conversion from dataless to stationxml, I will revert these units back to counts. This will at least keep our copy from being broken. Just point your code at our local FDSN service. I would rather not be surprised, by any more bugs like this in established processes. So I will go through ALL differences between converted files with a fine tooth comb. If it has become more trouble than it is worth, nothing is forcing us to use this converter. Patching xml post-conversion is too hacky. It is GPL3, so forking and patching to meet our needs is an option. I have already done this with the validator.

**Comment by timronan** [comment]
We have updated the counts issue in commit 297f43bf65b9aff2f2551a53c05acbdd1e3e2604, now counts converts to counts. The jar has been released under stationxml-seed-converter-2.0.9-SNAPSHOT.jar.

The converter automatically transforms specific units to their correct SI naming. The mapping can be found in the converter's documentation. Please report if the documentation is not clear. The unit transformation feature is not a bug, rather it was specifically requested and is designed to work with the stationxml-validator. The list of transformed units can be adjusted. If you find any other unit transformations that break dependencies please report therm and we can discuss different options. We are trying to develop tools that create clean and uniform data.

**Comment by jholland-usgs** [comment]
Thank you for switching this back to counts. I have tested the latest release and it is functioning as expected.

@timronan @yazan-iris @rcasey-iris 
I do want to emphasize, that I appreciate the work you are doing by creating the converter. I realize that you probably only get negative feedback (especially from me) in the form of bugs and change requests. I would rather that not be the case, so please accept my gratitude for the work you are doing. Thank you.

**Comment by timronan** [comment]
Thanks for the comments. We really appreciate the feedback, it helps us all develop a robust program that will be used and accepted by the community. Thanks for working with us.
