### ISSUE TITLE
Master is distorting normalization factor for Pole and Zeros Dataless-> SXML

### ISSUE THREAD

**Issue by timronan** [iris-edu/stationxml-seed-converter#43]
Normalization factor is being returned as 2.4596000538624E13 in output stationxml from an input dataless with the normalization factor of 2.4596E13. Digits are being are being appended normalization factor double during the conversion from dataless to stationxml. Test dataless file is attached. Look for UW.LON.SNN 2000-03-02 to 2011-08-26. 

[NormalizationFactor.zip](https://github.com/iris-edu/stationxml-seed-converter/files/4167987/NormalizationFactor.zip)

**Comment by chad-iris** [comment]
I believe the normalization frequency is also being "upgraded" in resolution.

We need to make sure the station/channel coordinate resolution is retained as documented also.

**Comment by timronan** [comment]
Test to isolate the normalization factor issue is introduced by commit 244d74adeac3f5489260543c0d3e574ebe87fdbb

**Comment by timronan** [comment]
This issue has been resolved by commits 5201ce3e683c5fb348a56743afde4e4c9b1a29b3 (java-4-seed), 2c2ac6826d40a477f5d8ecf8ae27ec90cb5dfa54 (fdsn-stationxml-model), and cef2666c5fcde9eb101f1ad00e4c415942bb184c (stationxml-seed-converter).
