### ISSUE TITLE
--prettyprint has no effect

### ISSUE THREAD

**Issue by crotwell** [iris-edu/stationxml-seed-converter#5]
Tried with both -p and --prettyprint but the output was all one line. Not very pretty...

Ran like:
`java -jar stationxml-converter-1.0.10.jar -x -so Dummy --prettyprint dataless.seed`

**Comment by timronan** [comment]
Refer to the [seed-xml-converter](https://github.com/iris-edu/seed-xml-converter). This is no longer an argument.
