### ISSUE TITLE
Converting from Seed to xml adds system UTC offset to date values

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-seed-converter#6]
**Problem:**
Dates are improperly converted from seed to xml. My system time offset from UTC appears to be added to each value.

12:00 becomes 18:00 (on dates that are MDT), 00:00 becomes 07:00 (on MST dates)

**Reproduction:**
I downloaded this stationxml
http://service.iris.edu/fdsnws/station/1/query?net=IU&sta=COLA&loc=*&cha=*&starttime=2009-07-09T00:00:00&endtime=2599-12-31T23:59:59&level=station&format=xml&nodata=404

I used the jar file from the release on github.

**Steps and output:**

Initial XML snippet
<Station code="COLA" **startDate="2009-07-09T00:00:00" endDate="2599-12-31T23:59:59"**

After Conversion to Seed (Still Correct)
java -jar ~/Downloads/stationxml-converter-1.0.10.jar --seed  -o cola.seed cola.xml
B050F13         Starting date:                         **2009,190,00:00:00.0000**
B050F14         Ending date:                           **2599,365,23:59:59.0000**

Reconvert to XML (Dates are now incorrect)
java -jar ~/Downloads/stationxml-converter-1.0.10.jar --xml --source='IRIS-DMC'  -o cola_1.xml cola.seed  
<Station code="COLA" startDate="**2009-07-09T06:00:00.000" endDate="2600-01-01T06:59:59.000**"

**Comment by yazan-iris** [comment]
Added a fix
