### ISSUE TITLE
Build failing for 2.1.1

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-seed-converter#67]
When I attempt to compile and package the jar, it fails to find one of the dependencies: edu.iris.dmc:fdsn-stationxml-model:jar:1.6.1.
```
Downloading from ossrh: https://oss.sonatype.org/content/repositories/releases/edu/iris/dmc/fdsn-stationxml-model/1.6.1/fdsn-stationxml-model-1.6.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.695 s
[INFO] Finished at: 2022-04-06T21:44:26Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project stationxml-seed-converter: Could not resolve dependencies for project edu.iris.dmc:stationxml-seed-converter:jar:2.1.1: Could not find artifact edu.iris.dmc:fdsn-stationxml-model:jar:1.6.1 in ossrh (https://oss.sonatype.org/content/repositories/releases) -> [Help 1]
```

I don't see v1.6.1 published on https://oss.sonatype.org/content/repositories/releases/edu/iris/dmc/fdsn-stationxml-model/

Similarly, stationxml-validator is failing to build because it can't find stationxml-seed-converter:jar:2.1.1.

Thank you

**Comment by timronan** [comment]
Please try your build process again. Note that stationxml-seed-converter:jar:2.1.1 is no longer using edu.iris.dmc:fdsn-stationxml-model:jar:1.6.1. edu.iris.dmc:fdsn-stationxml-model:jar:1.6.1 was rolled back to edu.iris.dmc:fdsn-stationxml-model:jar:1.6.0 until further notice.

**Comment by jholland-usgs** [comment]
I am able to build both projects now.  Thank you.
