### ISSUE TITLE
Unable to resolve dependency: oscache-mod2

### ISSUE THREAD

**Issue by jholland-usgs** [iris-edu/stationxml-seed-converter#7]
**Environment:**
Apache Maven 3.5.2
Java version: OpenJDK 1.8.0_171, vendor: Oracle Corporation

**Reproduction**
Clone project
Run: _mvn package_

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for edu.iris:stationxml-converter:jar:1.0.10
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 20, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-source-plugin is missing. @ line 40, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-eclipse-plugin is missing. @ line 29, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building station-seed-converter 1.0.10
[INFO] ------------------------------------------------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/opensymphony/oscache-mod2/2.1/oscache-mod2-2.1.pom
[WARNING] The POM for opensymphony:oscache-mod2:jar:2.1 is missing, no dependency information available
Downloading from central: https://repo.maven.apache.org/maven2/opensymphony/oscache-mod2/2.1/oscache-mod2-2.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.775 s
[INFO] Finished at: 2018-08-03T10:23:04-06:00
[INFO] Final Memory: 13M/295M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project stationxml-converter: Could not resolve dependencies for project edu.iris:stationxml-converter:jar:1.0.10: Could not find artifact opensymphony:oscache-mod2:jar:2.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by yazan-iris** [comment]
Not sure why we needed this, removed it for now.
